- name: Fetch HomeSetup
  ansible.builtin.git:
    repo: 'https://github.com/droopy4096/home_setup.git'
    dest: ~/work/home_setup

- name: Create bat config dir
  ansible.builtin.shell:
    cmd: mkdir -p ~/.config/bat
    creates: ~/.config/bat

- name: Create eza config dir
  ansible.builtin.shell:
    cmd: mkdir -p ~/.config/eza
    creates: ~/.config/eza

- name: Add homedir configs
  ansible.builtin.file:
    src: ~/work/home_setup/{{ item }}
    dest: ~/{{ item }}
    state: link
  with_items: "{{ homedir_configs }}"

- name: Add ${HOME}/bin dir
  ansible.builtin.file:
    path: ~/bin
    state: directory
    mode: "0750"

- name: Add homedir tools
  ansible.builtin.file:
    src: ~/work/home_setup/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  with_items:
    - k
    - h
    - dyff-R
    - my_ip

- name: Add bat alias on Debian
  ansible.builtin.lineinfile:
    path: ~/.zshrc.local
    create: true
    search_string: "alias bat=batcat"
    line: "alias bat=batcat"
    insertafter: EOF
    mode: "0640"
  when: 'ansible_os_family == "Debian"'

- name: Add exa alias
  ansible.builtin.lineinfile:
    path: ~/.zshrc.local
    create: true
    search_string: "alias ll="
    line: "alias ll='exa -l --git'"
    insertafter: EOF
    mode: "0640"

