---

- name: Get Worktree Tools
  ansible.builtin.git:
    repo: 'https://gitlab.com/dmakovey/worktree-tools.git'
    dest: ~/work/worktree-tools

- name: Setup Worktree Tools
  ansible.builtin.lineinfile:
    path: ~/.zshrc.local
    create: true
    search_string: "work/worktree-tools"
    line: ". ${HOME}/work/worktree-tools/worktree.zsh"
    insertafter: EOF
