- name: import Microsoft Signature
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: add VSCode repo
  ansible.builtin.shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  args:
    creates: /etc/yum.repos.d/vscode.repo
  become: true

- name: Install VSCode
  ansible.builtin.dnf: 
    name: code
    state: latest
  become: true