- name: Install pre-requisites
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family']|lower }}_packages.yml"

- name: Install LazyVim
  ansible.builtin.git:
    repo: 'https://github.com/LazyVim/starter'
    dest: ~/.config/nvim
